// Alexander Paryani
// 30 APR 2024
// Fortune Teller

// Name and School
console.log(`*** Script written by Alexander Paryani of Kalkaska High School ***`);
console.log('\n'); // Adds a blank line to output for spacing

// Countries and Jobs
const countries = ["Afghanistan","Albania","Algeria","Andorra","Angola","Anguilla","Antigua &amp; Barbuda","Argentina","Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bermuda","Bhutan","Bolivia","Bosnia &amp; Herzegovina","Botswana","Brazil","British Virgin Islands","Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Cape Verde","Cayman Islands","Chad","Chile","China","Colombia","Congo","Cook Islands","Costa Rica","Cote D Ivoire","Croatia","Cruise Ship","Cuba","Cyprus","Czech Republic","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Estonia","Ethiopia","Falkland Islands","Faroe Islands","Fiji","Finland","France","French Polynesia","French West Indies","Gabon","Gambia","Georgia","Germany","Ghana","Gibraltar","Greece","Greenland","Grenada","Guam","Guatemala","Guernsey","Guinea","Guinea Bissau","Guyana","Haiti","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Isle of Man","Israel","Italy","Jamaica","Japan","Jersey","Jordan","Kazakhstan","Kenya","Kuwait","Kyrgyz Republic","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Mauritania","Mauritius","Mexico","Moldova","Monaco","Mongolia","Montenegro","Montserrat","Morocco","Mozambique","Namibia","Nepal","Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria","Norway","Oman","Pakistan","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Puerto Rico","Qatar","Reunion","Romania","Russia","Rwanda","Saint Pierre &amp; Miquelon","Samoa","San Marino","Satellite","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","South Africa","South Korea","Spain","Sri Lanka","St Kitts &amp; Nevis","St Lucia","St Vincent","St. Lucia","Sudan","Suriname","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor L'Este","Togo","Tonga","Trinidad &amp; Tobago","Tunisia","Turkey","Turkmenistan","Turks &amp; Caicos","Uganda","Ukraine","United Arab Emirates","United Kingdom","Uruguay","Uzbekistan","Venezuela","Vietnam","Virgin Islands (US)","Yemen","Zambia","Zimbabwe"];
const jobs = ['Cost Estimator', 'Market Research Analyst', 'Web Developer', 'Janitor', 'Psychologist', 'Writer', 'Clinical Laboratory Technician', 'Court Reporter', 'Computer Systems Administrator', 'Auto Mechanic', 'Surveyor', 'Budget analyst', 'Systems Analyst', 'Police Officer', 'Actor', 'IT Manager', 'Patrol Officer', 'Landscape Architect', 'Public Relations Specialist', 'Medical Assistant', 'Computer Support Specialist', 'Civil Engineer', 'Chemist', 'Accountant', 'Recreational Therapist', 'Marketing Manager', 'Real Estate Agent', 'Electrician', 'Plumber', 'Radiologic Technologist', 'Judge', 'Urban Planner', 'Personal Care Aide', 'Veterinarian', 'Designer', 'Mechanical Engineer', 'Diagnostic Medical Sonographer', 'Database administrator', 'Bookkeeping clerk', 'Insurance Agent', 'Telemarketer', 'Massage Therapist', 'Paramedic', 'Marriage & Family Therapist', 'Editor', 'Architect', 'Compliance Officer', 'Electrical Engineer', 'Interpreter & Translator', 'Secretary', 'High School Teacher', 'Epidemiologist', 'Landscaper & Groundskeeper', 'Social Worker', 'Actuary', 'Mathematician', 'Childcare worker', 'Carpenter', 'Teacher Assistant', 'Logistician', 'Respiratory Therapist', 'Computer Programmer', 'School Counselor', 'Medical Secretary', 'Occupational Therapist', 'Photographer', 'Microbiologist', 'Statistician', 'Speech-Language Pathologist', 'Coach', 'Automotive mechanic', 'Physicist', 'Maintenance & Repair Worker', 'Physician', 'Reporter', 'Preschool Teacher', 'Sports Coach', 'Mason', 'Firefighter', 'Anthropologist', 'Zoologist', 'Professional athlete', 'Drafter', 'Elementary School Teacher', 'Art Director', 'Food Scientist', 'Farmer', 'Event Planner', 'Dental Hygienist', 'Human Resources Assistant', 'Bus Driver', 'Middle School Teacher', 'Construction Manager', 'College Professor', 'Artist', 'Hairdresser', 'Paralegal', 'Dentist', 'Fitness Trainer', 'Substance Abuse Counselor', 'Lawyer', 'Desktop publisher', 'Educator', 'Security Guard', 'Recreation & Fitness Worker', 'HR Specialist', 'Registered Nurse', 'Librarian', 'Computer Systems Analyst', 'Environmental scientist', 'Economist', 'School Psychologist', 'Referee', 'Receptionist', 'Physical Therapist', 'Historian', 'Software Developer', 'Customer Service Representative', 'Musician', 'Truck Driver', 'Painter', 'Cashier', 'Loan Officer', 'Executive Assistant', 'Computer Hardware Engineer', 'Pharmacist', 'Dancer', 'Housekeeper', 'Chef', 'Financial Advisor'];
const randCountry = countries[Math.floor(Math.random( ) * countries.length)];
const randJob = jobs[Math.floor(Math.random( ) * jobs.length)];
// console.log(randCountry);
// console.log(randJob);

// Random Years
const years =  Math.floor(Math.random() * 15);

// Ask for name
const firstName = prompt("Please enter your first name:\n");

// Display
const fortune = `In ${years} years, ${firstName} will be working as a(n) professional ${randJob} in ${randCountry}.`;

document.getElementById('myFortune').innerHTML = fortune;